version: '3'
services:
  database:
    container_name: database
    ports:
      - ${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}
    image: postgis/postgis:13-master
    restart: always
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  cache:
    container_name: cache
    image: redis:6
    restart: always
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - ${DIRECTUS_PORT}:${DIRECTUS_PORT}
    restart: always
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      # Directus
      KEY: ${KEY}
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CORS_ENABLED: ${CORS_ENABLED}
      PUBLIC_URL: ${PUBLIC_URL}

      # Database
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${POSTGRES_PORT_INTERNAL}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      # Cache
      CACHE_ENABLED: true
      CACHE_STORE: 'redis'
      CACHE_AUTO_PURGE: true
      REDIS: 'redis://cache:6379'

      # E-Mail
      EMAIL_TRANSPORT: smtp
      EMAIL_SMTP_HOST: smtp.strato.de
      EMAIL_SMTP_PORT: 465
      EMAIL_SMTP_USER: ${EMAIL_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SMTP_SECURE: true

networks:
  directus:
