import type { CamarillaAemter } from '$lib/types/zod/camarillaAemter';
import type { CamarillaBrujahKonflikt } from '$lib/types/zod/camarillaBrujahKonflikt';
import type { CamarillaCharaktere } from '$lib/types/zod/camarillaCharaktere';
import type { CamarillaSpielortFiles } from '$lib/types/zod/camarillaSpielortFiles';
import type { CamarillaUebersichtFiles } from '$lib/types/zod/camarillaUebersichtFiles';
import type { CamarillaZeittafelProtektorat } from '$lib/types/zod/camarillaZeittafelProtektorat';
import type { CharakterStatus } from '$lib/types/zod/charakterStatus';
import type { Clan } from '$lib/types/zod/clan';
import type { ClansFiles } from '$lib/types/zod/clansFiles';
import type { FileInformation } from '$lib/types/zod/fileInformation';
import type { FolderInformation } from '$lib/types/zod/folderInformation';
import type { Impressum } from '$lib/types/zod/impressum';
import type { Orga } from '$lib/types/zod/orga';
import type { OrgaRollen } from '$lib/types/zod/orgaRollen';
import type { ProjektUebersicht } from '$lib/types/zod/projektUebersicht';
import type { SabbatAemter } from '$lib/types/zod/sabbatAemter';
import type { SabbatCharakter } from '$lib/types/zod/sabbatCharakter';
import type { SabbatCharakterStatus } from '$lib/types/zod/sabbatCharakterStatus';
import type { SabbatPacks } from '$lib/types/zod/sabbatPacks';
import type { SabbatSpielortFiles } from '$lib/types/zod/sabbatSpielortFiles';
import type { SabbatUebersichtFiles } from '$lib/types/zod/sabbatUebersichtFiles';
import type { Sekten } from '$lib/types/zod/sekten';
import type { Spielort } from '$lib/types/zod/spielort';
import type { VereinAnsprechpersonen } from '$lib/types/zod/vereinAnsprechpersonen';
import type { VereinKontakt } from '$lib/types/zod/vereinKontakt';
import type { VereinParagraph86 } from '$lib/types/zod/vereinParagraph86';
import type { VereinRollen } from '$lib/types/zod/vereinRollen';
import type { VereinDatenschutz } from '$lib/types/zod/vereindatenschutz';
import type { W40KUebersichtFiles } from '$lib/types/zod/w40KUebersichtFiles';
import type { W40KSpielortFiles } from '$lib/types/zod/w40kSpielortFiles';
import type { WasIstVampireLive } from '$lib/types/zod/wasIstVampireLive';
import type { WasSindClans } from '$lib/types/zod/wasSindClans';
import { Directus } from '@directus/sdk';

type DirectusCollections = {
	impressum: Impressum;
	was_ist_vampire_live: WasIstVampireLive;
	clans: Clan;
	clans_files: ClansFiles;
	was_sind_clans: WasSindClans;
	camarilla_uebersicht: ProjektUebersicht;
	camarilla_uebersicht_files: CamarillaUebersichtFiles;
	camarilla_charaktere: CamarillaCharaktere;
	charakter_status: CharakterStatus;
	camarilla_aemter: CamarillaAemter;
	camarilla_spielort: Spielort;
	camarilla_spielort_files: CamarillaSpielortFiles;
	camarilla_zeittafel_protektorat: CamarillaZeittafelProtektorat;
	camarilla_brujah_konflikt: CamarillaBrujahKonflikt;
	camarilla_orga: Orga;
	orga_rollen: OrgaRollen;
	sekten: Sekten;
	sabbat_uebersicht: ProjektUebersicht;
	sabbat_uebersicht_files: SabbatUebersichtFiles;
	sabbat_charakter_status: SabbatCharakterStatus;
	sabbat_aemter: SabbatAemter;
	sabbat_packs: SabbatPacks;
	sabbat_charaktere: SabbatCharakter;
	sabbat_spielort: Spielort;
	sabbat_spielort_files: SabbatSpielortFiles;
	sabbat_orga: Orga;
	w40k_uebersicht: ProjektUebersicht;
	w40k_uebersicht_files: W40KUebersichtFiles;
	w40k_spielort: Spielort;
	w40k_spielort_files: W40KSpielortFiles;
	verein_rollen: VereinRollen;
	verein_ansprechpersonen: VereinAnsprechpersonen;
	verein_kontakt: VereinKontakt;
	verein_datenschutz: VereinDatenschutz;
	verein_paragraph_86_und_86a: VereinParagraph86;
	directus_files: FileInformation;
	directus_folders: FolderInformation;
};

export const directus = new Directus<DirectusCollections>(import.meta.env.VITE_DIRECTUS_URL);
